AWSTemplateFormatVersion: "2010-09-09"
Description: Stack for AppRunner

Parameters:
  ServiceName:
    Type: String
    Description: Name of the AppRunner Service
    Default: WebApp
  AppPort:
    Type: Number
    Description: The Port that the app will be listening on
    Default: 80
  ContainerImage:
    Type: String
    Description: container image uri
  ImageRepositoryType:
    Type: String
    Description: Type of the repository
    Default: ECR
  # Default values for Cpu and Memory are based on the AppRunner documentation
  # https://docs.aws.amazon.com/apprunner/latest/api/API_InstanceConfiguration.html
  Cpu:
    Type: Number
    Description: The CPU that the app will be using
    Default: 1
  Memory:
    Type: Number
    Description: The Memory that the app will be using
    Default: 2

Conditions:
  NeedsAccessRole:
    !Equals [!Ref ImageRepositoryType, 'ECR']

Resources:
  AccessRole:
    Type: AWS::IAM::Role
    Condition: NeedsAccessRole
    Properties:
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - build.apprunner.amazonaws.com
            Action: sts:AssumeRole
  
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
            Action: 'sts:AssumeRole'

  App:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Ref ServiceName
      SourceConfiguration:
        AuthenticationConfiguration: !If
          - NeedsAccessRole
          - AccessRoleArn: !GetAtt AccessRole.Arn
          - !Ref AWS::NoValue
        AutoDeploymentsEnabled: true
        ImageRepository:
          ImageIdentifier: !Ref ContainerImage
          ImageRepositoryType: !Ref ImageRepositoryType
          ImageConfiguration:
            Port: !Ref AppPort
      InstanceConfiguration:
        Cpu: !Sub ${Cpu} vCPU
        Memory: !Sub ${Memory} GB
        
Outputs:
  AppRunnerServiceArn:
    Description: ServiceArn of GitHub
    Value: !GetAtt App.ServiceArn
  AppRunnerServiceId:
    Description: AppRunnerServiceId
    Value: !GetAtt App.ServiceId
  AppRunnerServiceUrl:
    Description: AppRunnerServiceUrl
    Value: !GetAtt App.ServiceUrl